fix(modules): improve error handling during component installation and symlink creation

diff --git a/net.retrodeck.retrodeck.yml b/net.retrodeck.retrodeck.yml
--- a/net.retrodeck.retrodeck.yml
+++ b/net.retrodeck.retrodeck.yml
@@ -183,17 +183,25 @@ modules:
         echo "Found the following components in the components directory:"
         ls -1 *.tar.gz || echo "Wait... No components found actually."
         for archive in *.tar.gz; do
-          [ -e "$archive" ] || continue
-          echo "Extracting $archive..."
+
           component_name="${archive%.tar.gz}"
           component_path="${FLATPAK_DEST}/retrodeck/components/${component_name}"
+
+          echo "-------------------------------------"
+          echo "Installing component $component_name"
+          echo "-------------------------------------"
+
+          [ -e "$archive" ] || continue
+          echo "Extracting $archive..."
           mkdir -p "$component_path"
           tar -xzf "$archive" -C "$component_path" && echo "$archive extracted successfully in $component_path." || echo "Failed to extract $archive."
 
           # Symlink component_launcher.sh if it exists
           launcher_path="$component_path/component_launcher.sh"
           if [ -f "$launcher_path" ]; then
-            ln -sf "$launcher_path" "${FLATPAK_DEST}/bin/${component_name}"
+            ln -sf "$launcher_path" "${FLATPAK_DEST}/bin/${component_name}" || echo "Failed to create symlink for $component_name"
+          else
+            echo "Warning: component_launcher.sh not found for $component_name, skipping symlink creation."
           fi
         done
       - |
