LLVM: debugging as seems to be not included

diff --git a/net.retrodeck.retrodeck.yml b/net.retrodeck.retrodeck.yml
--- a/net.retrodeck.retrodeck.yml
+++ b/net.retrodeck.retrodeck.yml
@@ -4,8 +4,6 @@ runtime-version: "6.7"
 sdk: org.kde.Sdk
 base: org.electronjs.Electron2.BaseApp            # Needed for Steam ROM Manager
 base-version: "22.08"
-sdk-extensions:
-  - org.freedesktop.Sdk.Extension.llvm18        # Needed for RPCS3
 command: retrodeck.sh
 
 finish-args:
@@ -686,19 +684,20 @@ modules:
     buildsystem: simple
     build-commands:
       - |
-          # Search for missingl ibraries in our libtmp folder
+          # Search for missing libraries in our libtmp folder
           missing_libs=$(find "${FLATPAK_DEST}/bin" -type f -exec ldd {} + 2>/dev/null | grep "not found" | awk '{print $1}' | sort | uniq)
           
-          # for some reason these libraries are not recognized as missing so we mantain this list
-          manually_imported="libpostproc.so.56 libswscale.so.6 libshaderc_shared.so.1 libbz2.so.1.0 libaio.so.1 ld-linux.so.2 libvpx.so.9 libzmusic.so.1 libicuuc.so.73"
-
+          # Manually specified libraries that are not automatically detected
+          manually_imported="libpostproc.so.56 libswscale.so.6 libshaderc_shared.so.1 libbz2.so.1.0 libaio.so.1 ld-linux.so.2 libvpx.so.9 libzmusic.so.1 libicuuc.so.73 libLLVM.so.18.1"
+          
+          # Combine detected missing libraries and manually specified ones
           missing_libs="$missing_libs $manually_imported"
 
-          # Origin paths
+          # Source paths
           src_dir="${FLATPAK_DEST}/retrodeck/tmplib"
           src_debug_dir="${FLATPAK_DEST}/retrodeck/tmplib/debug"
 
-          # Destionation paths
+          # Destination paths
           dest_dir="${FLATPAK_DEST}/lib"
           dest_debug_dir="${FLATPAK_DEST}/retrodeck/lib/debug"
           
@@ -710,18 +709,20 @@ modules:
             local dest=$3
             for lib in $missing_libs; do
               if [[ -f "$src/$lib" ]]; then
-                cp "$src/$lib" "$dest"
-                echo "Copied \"$lib\" to \"$dest\""
+                cp "$src/$lib" "$dest" && echo "Copied \"$lib\" to \"$dest\"" || echo "Error copying \"$lib\""
               elif [[ -f "$src_debug/$lib.debug" ]]; then
-                cp "$src_debug/$lib.debug" "$dest"
-                echo "Copied debug version of \"$lib\" to \"$dest\""
+                cp "$src_debug/$lib.debug" "$dest" && echo "Copied debug version of \"$lib\" to \"$dest\"" || echo "Error copying debug version of \"$lib\""
+              else
+                echo "Library \"$lib\" not found in \"$src\" or \"$src_debug\""
               fi
             done
           }
 
+          # Copy libraries from source to destination
           copy_missing_libs "$src_dir" "$src_debug_dir" "$dest_dir"
           copy_missing_libs "$src_debug_dir" "$dest_debug_dir"
 
+          # Remove temporary source directory to free up space
           rm -rf "$src_dir"
 
   - name: retrodeck
